apiVersion: v1
kind: Secret
metadata:
  name: gitlab-keycloak-oidc-secret
  namespace: gitlab
stringData:
  provider: |
    {
      "name": "openid_connect",
      "args": {
        "scope": ["openid", "profile", "email"],
        "response_type": "code",
        "issuer": "http://k-keycloakadm.softworks.co.kr:31370/auth/realms/kubeworks",
        "discovery": true,
        "client_auth_method": "query",
        "uid_field": "preferred_username",
        "client_id": "gitlab",
        "client_secret": "7xrYVga9Gliw2vuXtaGAcNOVAjluj10l",
        "redirect_uri": "https://k-gitlab.softworks.co.kr:31089/users/auth/openid_connect/callback"
      }
    }