apiVersion: v1
kind: Secret
metadata:
  name: gitlab-keycloak-oidc-secret
  namespace: gitlab
stringData:
  provider: |
    name: 'saml'
    label: 'keycloak'
    args:
        assertion_consumer_service_url: 'https://k-gitlab.softworks.co.kr:31098/users/auth/saml/callback'
        idp_cert_fingerprint: 'd26c909cde8663f14217efe41b3528a70aab3dce'
        idp_sso_target_url: 'http://k-keycloak.softworks.co.kr:31370/auth/realms/kebeworks/protocol/saml/clients/gitlab'
        issuer: 'gitlab'
        name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'