apiVersion: v1
kind: Secret
metadata:
  name: omniauth-saml
  namespace: gitlab
type: Opaque
stringData:
  provider: |
    name: 'saml'
    label: 'SAML'
    groups_attribute: 'roles'
    required_groups: ['gitlab.softworks.co.kr:external','gitlab.softworks.co.kr:admin']
    external_groups: ['gitlab.softworks.co.kr:external']
    admin_groups: ['gitlab.softworks.co.kr:admin']
    args:
      assertion_consumer_service_url: 'https://k-gitlab.softworks.co.kr:31098/users/auth/saml/callback'
      idp_cert_fingerprint: 'd26c909cde8663f14217efe41b3528a70aab3dce'
      idp_sso_target_url: 'http://k-keycloak.softworks.co.kr:31370/realms/kubeworks/protocol/saml/clients/gitlab'
      issuer: 'k-gitlab.softworks.co.kr'
      name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'