apiVersion: v1
kind: Secret
metadata:
  name: omniauth-saml
  namespace: gitlab
type: Opaque
stringData:
  provider: |
    name: 'saml'
    label: 'SAML'
    groups_attribute: 'roles'
    required_groups: ['gitlab.softworks.co.kr:external','gitlab.softworks.co.kr:admin']
    external_groups: ['gitlab.softworks.co.kr:external']
    admin_groups: ['gitlab.softworks.co.kr:admin']
    args:
      assertion_consumer_service_url: 'https://k-gitlab.softworks.co.kr:31098/users/auth/saml/callback'
      idp_cert_fingerprint: 'EE:C4:CB:CF:9F:C4:58:F6:1F:D7:1F:41:FF:3A:A3:12:18:B3:07:30:F9:F6:76:FB:8E:DE:06:3E:8F:3B:D6:7B'
      idp_sso_target_url: 'http://k-keycloakadm.softworks.co.kr:31370/realms/kubeworks/protocol/saml/clients/gitlab'
      allowed_clock_drift: 5
      issuer: 'gitlab'
      attribute_statments:
        first_name: ['first_name']
        last_name: ['last_name']
        name: ['name']
        username: ['name']
        email: ['email']
      name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'