apiVersion: v1
kind: Service
metadata:
  name: kubectl01
  labels:
    app: kubectl01
spec:
  type: ClusterIP
  # ports:
  # - name: http
  #   protocol: TCP
  #   port: 8080
  #   targetPort: 80
  selector:
    app: kubectl01
