apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: "httpd"
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30202
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: "httpd"
