apiVersion: apps/v1
kind: Deployment
metadata:
  name: demofe
  labels:
    app: "demofe"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demofe"
  template:
    metadata:
      labels:
        app: "demofe"
    spec:
      containers:
      - name: demofe
#        image: node:18.13.0-alpine
        image: kimjonggu/demo_fe
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        # command: ["/bin/sh","-ec","while :; do echo 'Hello World'; sleep 5; done"]
      # imagePullSecrets:
      # - name: regcred
