apiVersion: v1
kind: Service
metadata:
  name: demofe
  labels:
    app: "demofe"
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30202
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: "demofe"
