apiVersion: v1
kind: Service
metadata:
  name: webssh2
  labels:
    app: "webssh2"
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30093
    protocol: TCP
    port: 2222
    targetPort: 2222
  selector:
    app: "webssh2"
