apiVersion: apps/v1
kind: Deployment
metadata:
  name: webssh2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webssh2
  template:
    metadata:
      labels:
        app: webssh2
    spec:
      containers:
      - name: webssh2
        image: psharkey/webssh2:latest
        ports:
        - containerPort: 2222