service:
  type: NodePort
  nodePorts:
    http: "30180"
    https: "30181"
auth:
  adminPassword: "admin1234"
  managementPassword: "admin1234"
# ingress:
#   enabled: true
#   ingressClassName: nginx # 사용하는 ingress class
#   hostname: kube01.softworks.co.kr # 원하는 domain
postgresql:
  enabled: true
  auth:
    pastgresPassword: ""
    username: keycloak
    password: "keycloak"
    database: keycloak
    existingSecret: ""
  architecture: standalone
