global:
  storageClass: nfs-client
# service:
#   type: NodePort
#   nodePorts:
#     http: 30083
#     https: 30084
auth:
  adminUser: admin
  adminPassword: "admin1234"
  managementPassword: "admin1234"
adminIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: k-keycloakadm.softworks.co.kr
keycloakConfigCli:
  enabled: true
  configuration:
    master.json: |
      {
        "realm" : "master",
        "attributes": {
          "frontendUrl": "http://k-keycloakadm.softworks.co.kr:31370"
        }
      }

ingress:
  enabled: true
  ingressClassName: nginx # 사용하는 ingress class
  hostname: k-keycloak-client.softworks.co.kr # 원하는 domain
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"  #test
  #   nginx.ingress.kubernetes.io/session-cookie-name: "KEYCLOAK_SESSION" #test
  #   nginx.ingress.kubernetes.io/session-cookie-hash: "sha1" #test
  #   nginx.ingress.kubernetes.io/session-cookie-path: "/" #test
  #   nginx.ingress.kubernetes.io/session-cookie-samesite: "None" #test
  #   nginx.ingress.kubernetes.io/session-cookie-secure: "true" #test

    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # nginx.ingress.kubernetes.io/proxy-buffering: "on"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # nginx.ingress.kubernetes.io/session-cookie-name: "KEYCLOAK_SESSION"
    # nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # nginx.ingress.kubernetes.io/session-cookie-path: "/"
    # nginx.ingress.kubernetes.io/session-cookie-samesite: "None"
    # nginx.ingress.kubernetes.io/session-cookie-secure: "true"

  # tls:
  #   - hosts:
  #     - k-keycloak.softworks.co.kr
  #     secretName: keycloak-tls-secret

# keycloak:
#   proxy: edge
# extraEnv:
#   - name: KEYCLOAK_COOKIE_SECURE
#     value: "true"
#   - name: KEYCLOAK_COOKIE_SAME_SITE
#     value: "None"
#   - name: PROXY_ADDRESS_FORWARDING
#     value: "true"

postgresql:
  enabled: true
  auth:
    # postgresPassword: admin1234
    username: keycloak
    password: "keycloak"
    database: keycloak
    existingSecret: ""
  architecture: standalone