global:
  storageClass: nfs-client
# service:
#   type: NodePort
#   nodePorts:
#     http: 30083
#     https: 30084
auth:
  adminPassword: "admin1234"
  managementPassword: "admin1234"
ingress:
  enabled: true
  ingressClassName: nginx # 사용하는 ingress class
  hostname: k-keycloak.softworks.co.kr # 원하는 domain

keycloak:
  proxy: edge

postgresql:
  enabled: true
  auth:
    # postgresPassword: admin1234
    username: keycloak
    password: "keycloak"
    database: keycloak
    existingSecret: ""
  architecture: standalone