apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data10G-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/data10G-0"
  persistentVolumeReclaimPolicy: Retain