apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jupyterhub
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/jupyterhub"
  persistentVolumeReclaimPolicy: Retain