apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data10-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/data10-1"
  persistentVolumeReclaimPolicy: Retain