kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc
  namespace: volume
annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/no-provisioner