kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
namespace: volume
name: my-storage
annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/host-path