global:
  edition: ce #on-prem
  hosts:
    domain: softworks.co.kr  #on-prem
    # externalIP: 
    https: true
    gitlab:
      name: k-gitlab.softworks.co.kr
      https: true
    minio:
      name: k-minio.softworks.co.kr
      https: true
    registry:
      name: k-registry.softworks.co.kr
      https: true
  ingress:
    configureCertmanager: false #on-prem
    provider: nginx #on-prem
    class: nginx  #on-prem
    enabled: true #on-prem
    tls: 
      enabled: true #on-prem
certmanager-issuer:
  email: jmsk80@softworks.co.kr


# postgresql:
#   image:
#     tag: 

certmanager:
  installCRDs: false  #on-prem
  install: false
nginx-ingress:
  enabled: false  #on-prem
prometheus:
  install: false  #on-prem
gitlab-runner:
  install: false  #on-prem
upgradeCheck:
  enabled: false