global:
  edition: ce #on-prem
  hosts:
    domain: softworks.co.kr  #on-prem
    https: false
    # externalIP: 
    gitlab:
      name: k-gitlab.softworks.co.kr
      https: false
    minio:
      name: k-minio.softworks.co.kr
      https: true
    registry:
      name: k-registry.softworks.co.kr
      https: true
  ingress:
    configureCertmanager: false #on-prem
    provider: nginx #on-prem
    class: nginx  #on-prem
    enabled: true #on-prem
    tls: 
      enabled: true #on-prem
  # omniauth:
  #   enabled: true
  #   providers:
  #     - name: 'openid_connect'
  #       label: 'keycloak'
  #       args:
  #         name: 'openid_connect'
  #         scope: ['openid', 'profile', 'email']
  #         response_type: 'code'
  #         issuer: 'http://k-keycloak.softworks.co.kr:31370/auth/realms/kubeworks'
  #         discovery: true
  #         client_auth_method: 'query'
  #         uid_field: 'preferred_username'
  #         client_id: 'gitlab'
  #         client_secret: '7xrYVga9Gliw2vuXtaGAcNOVAjluj10l'  # 여기에도 동일한 비밀 키를 넣습니다
  #         redirect_uri: 'https://k-gitlab.softworks.co.kr:31089/users/auth/openid_connect/callback'
  appConfig:
    # omniauth:
      # enabled: true
      # auto_sign_in_with_provider: 'openid_connect'
      # external_providers: ['openid_connect']
      # allow_single_sign_on: ['openid_connect']
      # block_auto_created_users: false
      # auto_link_saml_user: false
      # sync_profile_from_provider: ['openid_connect']
      # sync_profile_attributes: ['email', 'name']
      # sync_ssh_keys: false
      # providers:
      #   - secret: gitlab-keycloak-oidc-secret
    omniauth:
      enabled: true
      allowSingleSignOn: ['saml']
      autoSignInWithProvider: 'saml'
      blockAutoCreatedUsers: false
      # syncProfileFromProvider: ['saml']
      # syncProfileAttributes: ['email']
      autoLinkSamlUser: true
      providers:
        # - secret: omniauth-saml
        - configmap: 
          name: omniauth-saml-cm


certmanager-issuer:
  email: jmsk80@softworks.co.kr


# postgresql:
#   image:
#     tag: 

certmanager:
  installCRDs: false  #on-prem
  install: false
nginx-ingress:
  enabled: false  #on-prem
prometheus:
  install: false  #on-prem
gitlab-runner:
  install: false  #on-prem
upgradeCheck:
  enabled: false