controller:
  jenkinsUrl: http://k-jenkins.softworks.co.kr:31370
  installPlugins:
    - kubernetes:latest  
    # - keycloak:2.3.2
    - configuration-as-code:latest
    # - oidc-plugin:latest
    # - oauth-credentials:latest    
    - oic-auth:latest
    - role-strategy
  javaOpts: "-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true"

  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  JCasC:
    defaultConfig: true  
    securityRealm: |-
      oic:
        clientId: "jenkins"
        clientSecret: "3bZvxR0mn0TaSjn52eOit68a21cAjlyL"
        wellKnownOpenIDConfigurationUrl: "http://k-keycloak.softworks.co.kr:31370/realms/kubeworks/.well-known/openid-configuration"
        tokenServerUrl: "http://k-keycloak.softworks.co.kr:31370/realms/kubeworks/protocol/openid-connect/token"
        authorizationServerUrl: "http://k-keycloak.softworks.co.kr:31370/realms/kubeworks/protocol/openid-connect/auth"
        scopes: "openid profile email"
        disableSslVerification: false
        endSessionEndpoint: "http://k-keycloak.softworks.co.kr:31370/realms/home/protocol/openid-connect/logout"
        escapeHatchEnabled: false
        logoutFromOpenidProvider: true
        userNameField: "preferred_username"
        emailFieldName: "email"
        groupsFieldName: "groups"
  #   authorizationStrategy: |-
  #     roleBased:
  #       roles:
  #         global:
  #           - name: "admin"
  #             description: "Jenkins administrators"
  #             permissions:
  #               - "Overall/Administer"
  #             entries:
  #               - group: "jenkins-admin"
  #           - name: "user"
  #             description: "jenkins users"
  #             permissions:
  #               - "Overall/Read"
  #               - "Job/Read"
  #             entries:
  #               - group: "jenkins-user"
  #           - name: "readonly"
  #             description: "Read-only users"
  #             permissions:
  #               - "Overall/Read"
  #               - "Job/Read"
  #             entries:
  #               - user: "authenticated"
