apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: "httpd"
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30092
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: "httpd"
