apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubebox
  template:
    metadata:
      labels:
        app: kubebox
    spec:
      containers:
      - name: kubebox
        image: astefanutti/kubebox:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
          # subPath: config
      volumes:
      - name: kubeconfig
        configMap:
          name: kubeconfig