apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: "httpd"
spec:
  serviceAccountName: xterm-user
  replicas: 1
  selector:
    matchLabels:
      app: "httpd"
  template:
    metadata:
      labels:
        app: "httpd"
    spec:
      containers:
      - name: httpd
#        image: node:18.13.0-alpine
        image: kimjonggu/xtermjs:0.01
        ports:
        - name: http
          containerPort: 3000
        command: ["/bin/sh","-ec","while :; do echo 'Hello World'; sleep 5; done"]
      # imagePullSecrets:
      # - name: regcred
