apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sa-test
    namespace: jenkins
kind: List
metadata:
  resourceVersion: ""

---

apiVersion: v1
kind: Secret
metadata:
  name: sa-test
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: "sa-test"  
type: kubernetes.io/service-account-token