apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-dec
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: dev Project
  sourceRepos:
  - '*'

  destinations:
  - namespace: kubeworks-cluster
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
