apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl01
spec:
  selector:
    matchLabels:
      app: kubectl01
  template:
    metadata:
      name: kubectl01
      labels:
        app: kubectl01
    spec:
      containers:
      - name: kubectl
        image: lachlanevenson/k8s-kubectl
        ttyEnabled: true
        command: ["/bin/sh","-ec","while :; do echo 'Hello World'; sleep 5; done"]
        # ports:
        # - name: http
        #   containerPort: 8080
        #   protocol: TCP
