apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  namespace: k8s-kubectl
  name: kubeworks-user-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeworks-user-role
subjects:
- kind: ServiceAccount
  name: kubectl-user
  namespace: k8s-kubectl