apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: context-sa-test
    namespace: argo
kind: List
metadata:
  resourceVersion: ""

---

apiVersion: v1
kind: Secret
metadata:
  name: context-sa-test
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: "context-sa-test"  
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: context-sa-test-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: context-sa-test
  namespace: argo