apiVersion: v1
kind: ServiceAccount
metadata:
  name: webssh2-sa
  namespace: websshk
---
apiVersion: v1
kind: Secret
metadata:
  name: webssh2-sa-token
  annotations:
    kubernetes.io/service-account.name: webssh2-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webssh2-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webssh2-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: webssh2-sa
    namespace: websshk
roleRef:
  kind: ClusterRole
  name: webssh2-cluster-role
  apiGroup: rbac.authorization.k8s.io