apiVersion: v1
kind: ServiceAccount
metadata:
  name: webssh2-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webssh2-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webssh2-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: webssh2-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: webssh2-cluster-role
  apiGroup: rbac.authorization.k8s.io