apiVersion: v1
kind: Service
metadata:
  name: webssh2-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: webssh2
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30094
      targetPort: 2222