expose:
  type: ingress
  ingress:
    hosts:
      core: k-harbor.softworks.co.kr:31370
      notary: notary.k-harbor.softworks.co.kr:31370
    controller: default
    className: "nginx"
externalURL: http://k-harbor.softworks.co.kr:31370
registry:
  credentials:
    username: "admin"
    password: "admin1234"