hostname: harbor.my-domain.com

expose:
  type: ingress
  ingress:
    hosts:
      core: k-harbor.softworks.co.kr
      notary: notary.k-harbor.softworks.co.kr
    # annotations:
    #   kubernetes.io/ingress.class: "nginx"
    className: "nginx"
    tls: []
harborAdminPassword: "admin1234"

oidc:
  enabled: true
  issuer: "https://k-keycloak.softworks.co.kr:31089/realms/kubeworks"
  clientId: "harbor"
  clientSecret: "j6pwzWswgtjdbzLSqalk6pipAQW8cCcr"
  scope: "openid,profile,email"
  verifyCert: true
  autoOnboard: true
  groupsClaim: "groups"
  adminGroup: "harbor-admins"
  userClaim: "preferred_username"

persistence:
  persistentVolumeClaim:
    registry:
      size: 50Gi
    chartmuseum:
      size: 5Gi
    jobservice:
      size: 1Gi
    redis:
      size: 1Gi
    trivy:
      size: 5Gi