apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm-export.json: |
    {
      "realm": "kubeworks",
      "clients": [
        {
          "clientId": "gitlab",
          "enabled": true,
          "protocol": "openid-connect",
          "clientAuthenticatorType": "client-secret",
          "secret": "7xrYVga9Gliw2vuXtaGAcNOVAjluj10l",
          "redirectUris": ["https://k-gitlab.softworks.co.kr:31089/users/auth/openid_connect/callback"],
          "webOrigins": ["https://k-gitlab.softworks.co.kr:31089"],
          "publicClient": false,
          "fullScopeAllowed": true,
          "attributes": {
            "client.secret.creation.time": "1625836769",
            "access.token.lifespan": "600"
          }
        }
      ]
    }