hub:
  config:
    Authenticator:
      admin_users:
      - adminuser1
      - adminuser2
  scheduling:
    userScheduler:
      enabled: false
  # service:
  #   type: NodePort
proxy:
  service:
    type: NodePort