# hub:
#   config:
#     Authenticator:
#       admin_users:
#       - adminuser1
#       - adminuser2
#   scheduling:
#     userScheduler:
#       enabled: false
  # service:
  #   type: NodePort
  db:
    pvc:
      storageClassName: nfs-client
proxy:
  service:
    type: NodePort