apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: "httpd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "httpd"
  template:
    metadata:
      labels:
        app: "httpd"
    spec:
      containers:
      - name: httpd
#        image: node:18.13.0-alpine
        image: kimjonggu/uploader:0.0.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: uploader-pvc
          mountPath: /usr/share/nginx/html
        # command: ["/bin/sh","-ec","while :; do echo 'Hello World'; sleep 5; done"]
      # imagePullSecrets:
      # - name: regcred
      volumes:
      - name: uploader-pvc  # 볼륨 이름
        persistentVolumeClaim:
          claimName: uploader-pvc  # PersistentVolumeClaim 이름
