# Kafka Image configuration
image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.5.0-debian-10-r0
  pullPolicy: IfNotPresent
  pullSecrets: []

# Zookeeper settings
zookeeper:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: bitnami/zookeeper
    tag: 3.8.0-debian-10-r0
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

# Kafka Broker configuration
replicaCount: 1
configurationOverrides: {}
listeners:
  plain: {}
  tls: {}
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

# External Zookeeper configuration
externalZookeeper:
  enabled: false
  servers: []

# Metrics exporter configuration
metrics:
  kafka:
    jmx:
      enabled: false
  zookeeper:
    jmx:
      enabled: false