persistence:
  enabled: true
  existingClaim: "kafka-data-pvc"
 
zookeeper:
  persistence:
    existingClaim: "kafka-zoo-pvc"
    
    
externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      - 30001
    useHostIPs: true
    domain: "kube01.softworks.co.kr"