# persistence:
#   enabled: true
#   existingClaim: "kafka-data-pvc"
 
# zookeeper:
#   persistence:
#     existingClaim: "kafka-zoo-pvc"
    
# externalAccess:
#   enabled: true
#   controller:
#     service:
#       type: NodePort
#       nodePorts:
#         - 30001
#       useHostIPs: true
#       domain: "kube01.softworks.co.kr"

service:
  type: NodePort
  nodePorts:
    client: 32092
    external: ""