apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: "httpd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "httpd"
  template:
    metadata:
      labels:
        app: "httpd"
    spec:
      containers:
      - name: httpd
#        image: node:18.13.0-alpine
        image: kimjonggu/demo_gw
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP          
        # command: ["/bin/sh","-ec","while :; do echo 'Hello World'; sleep 5; done"]
      # imagePullSecrets:
      # - name: regcred
