apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: "httpd"
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30300
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: "httpd"
